apiVersion: v1
kind: Service
metadata:
  name: despachos
  namespace: innovatech
spec:
  type: ClusterIP
  selector:
    app: despachos
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
